version: '3.8'

services:
  python:
    build:
      context: .
      dockerfile: infra/docker/Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      localstack:
        condition: service_healthy  # Attendre que LocalStack soit prêt
    environment:
      - PYTHONPATH=/app
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ENDPOINT_URL=http://localstack:4566

  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - LAMBDA_EXECUTOR=docker
      - DEFAULT_REGION=us-east-1
    ports:
      - "4566:4566"
    volumes:
      - './localstack:/var/lib/localstack'
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: >
      sh -c "
      until curl -s http://localhost:4566/_localstack/health | grep '\"s3\": \"running\"'; do
        echo 'Waiting for LocalStack to be ready...';
        sleep 2;
      done;
      echo 'Creating S3 buckets...';
      aws --endpoint-url=http://localhost:4566 s3 mb s3://raw &&
      aws --endpoint-url=http://localhost:4566 s3 mb s3://staging &&
      aws --endpoint-url=http://localhost:4566 s3 mb s3://curated;
      echo 'All buckets created!';
      exec localstack start"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 5s
      retries: 5
      start_period: 5s
      timeout: 5s
